// because linguist -*- mode: c;-*-

/*
 * CLASS DEFINITIONS
 *
 * Class identifiers are defined as a consecutive list of constants in aow2scrp.acs.
 * This function inits classes by setting values in the two-dimensional Classes
 * array. The array is accessed using constant keys (CK_NAME et al)
 *
 * The c variable is first init to set the class identifier (this way it doesn't have
 * to be copied and changed every time properties are copied from one class to another)
 * Technically this doesn't have to be done but it results in less gray hair.
 *
 * To add items, the AddClassItem function is used. Don't alter CK_NUMITEMS directly under
 * any circumstance! It will be set automagically. The first item added to the class defines
 * the primary weapon - the default weapon the player will be holding after the class is
 * purchased.
 *
 * Class keys:
 * - CK_NAME:     Name of the class, e.g. "Gunman"
 * - CK_SPEED:    Speed factor of the class. 1.0 is default AOW player speed
 * - CK_COST:     Price of the class, in credits. 0 means free.
 * - CK_C4:       Amount of timed C4 bricks the class gets. Default: 1
 * - CK_GERNADES: [sic] Amount of frag grenades the class gets. Default: 1
 * - CK_DEP:      Building dependency: one of DEP_BARRACKS, DEP_REFINERY, DEP_CENTRE. Default: 0 (no dep)
 * - CK_ARMORNUM: Armor grade of the class, default: 0
 * - CK_ARMORMOD: Armor modifier: ARMOD_FIRE, ARMOD_CHEM, ARMOD_LASER, ARMOD_EXPLO, ARMOD_BULLET, 0 for none
 * - CK_FLAGS:    Flag modifiers:
 * ---- CF_SUPPORT:    Class is support and deals less damage.
 * ---- (more to follow)
 * - CK_NUMITEMS: Amount of items the class has (again, don't set this directly! Only ever read it!)
 *
 * After CK_NUMITEMS (which is the last key), the class definition in the table is continued with
 * CK_NUMITEMS amount of name-and-amount pairs. The GetClassItemName and GetClassItemAmount functions
 * should be used to access these item definitions. They take the class id and item number (which in turn
 * ranges [0, CK_NUMITEMS - 1])
 */

function void LoadClassDefinitions (void)
{
	int c;

	c = CLASS_GUNMAN;
	Classes[c][CK_NAME] = "Gunman";
	AddClassItem(c, "SubMachineGun", 1);
	AddClassItem(c, "SubAmmo", 225);

	c = CLASS_ENGINEER;
	Classes[c][CK_NAME] = "Engineer";
	Classes[c][CK_SPEED] = 0.8;
	Classes[c][CK_FLAGS] = (CF_SUPPORT);
	AddClassItem(c, "RepairGun", 1);

	c = CLASS_MINIGUNNER;
	Classes[c][CK_NAME] = "Minigunner";
	Classes[c][CK_COST] = 400;
	Classes[c][CK_SPEED] = 0.7;
	Classes[c][CK_ARMORNUM] = 1;
	Classes[c][CK_GERNADES] = 2;
	AddClassItem(c, "GatlingGun", 1);
	AddClassItem(c, "ChainAmmo", 250);

	c = CLASS_TECHNICIAN;
	Classes[c][CK_NAME] = "Technician";
	Classes[c][CK_COST] = 200;
	Classes[c][CK_SPEED] = 0.8;
	Classes[c][CK_ARMORNUM] = 1;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_C4] = 2;
	Classes[c][CK_FLAGS] = (CF_SUPPORT);
	AddClassItem(c, "RepairGun", 1);
	AddClassItem(c, "RepairGunUpgrade", 1);
	AddClassItem(c, "SubMachineGun", 1);
	AddClassItem(c, "ProxyMine", 4);
	AddClassItem(c, "ProxyMineCount", 4);

	c = CLASS_FLAMER;
	Classes[c][CK_NAME] = "Flamer";
	Classes[c][CK_COST] = 450;
	Classes[c][CK_SPEED] = 0.7;
	Classes[c][CK_ARMORNUM] = 1;
	Classes[c][CK_ARMORMOD] = ARMOD_FIRE;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_DEP] = DEP_BARRACKS;
	AddClassItem(c, "Flamer", 1);
	AddClassItem(c, "FlamerAmmo", 300);
	AddClassItem(c, "PhosphorusGrenadeAmmo", 4);
	AddClassItem(c, "SubMachineGun", 1);
	AddClassItem(c, "SubAmmo", 225);

	c = CLASS_RIFLEMAN;
	Classes[c][CK_NAME] = "Rifleman";
	Classes[c][CK_COST] = 200;
	Classes[c][CK_SPEED] = 0.9;
	Classes[c][CK_ARMORNUM] = 1;
	AddClassItem(c, "Rifle", 1);
	AddClassItem(c, "RifleAmmo", 40);
	AddClassItem(c, "RifleGrenadeAmmo", 8);

	c = CLASS_ASSAULTGUNNER;
	Classes[c][CK_NAME] = "Assault Gunner";
	Classes[c][CK_COST] = 300;
	Classes[c][CK_SPEED] = 0.9;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 1;
	AddClassItem(c, "AssaultRifle", 1);
	AddClassItem(c, "ARAmmo", 150);

	c = CLASS_GRENADIER;
	Classes[c][CK_NAME] = "Grenadier";
	Classes[c][CK_COST] = 550;
	Classes[c][CK_SPEED] = 0.8;
	Classes[c][CK_GERNADES] = 4;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_EXPLO;
	Classes[c][CK_DEP] = DEP_BARRACKS;
	AddClassItem(c, "GrenadeLauncher", 1);
	AddClassItem(c, "GrenadeAmmo", 42);
	AddClassItem(c, "Rifle", 1);
	AddClassItem(c, "RifleAmmo", 40);
	AddClassItem(c, "RifleGrenadeAmmo", 8);

	c = CLASS_ROCKETEER;
	Classes[c][CK_NAME] = "Rocket Soldier";
	Classes[c][CK_COST] = 500;
	Classes[c][CK_SPEED] = 0.75;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_EXPLO;
	Classes[c][CK_DEP] = DEP_BARRACKS;
	AddClassItem(c, "Classmissilelauncher", 1);
	AddClassItem(c, "MissileLauncher", 1);
	AddClassItem(c, "MissileAmmo", 20);
	AddClassItem(c, "Rifle", 1);
	AddClassItem(c, "RifleAmmo", 40);
	AddClassItem(c, "RifleGrenadeAmmo", 8);

	c = CLASS_STEALTH;
	Classes[c][CK_NAME] = "Stealth Trooper";
	Classes[c][CK_COST] = 600;
	Classes[c][CK_SPEED] = 0.95;
	Classes[c][CK_GERNADES] = 1;
	Classes[c][CK_ARMORNUM] = -1;
	Classes[c][CK_ARMORMOD] = ARMOD_LASER;
	AddClassItem(c, "StealthLaserRifle", 1);
	AddClassItem(c, "EnergyAmmo", 300);
	AddClassItem(c, "Knife", 1);

	c = CLASS_GAUSSGUNNER;
	Classes[c][CK_NAME] = "Gauss Gunner";
	Classes[c][CK_COST] = 600;
	Classes[c][CK_SPEED] = 0.8;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_LASER;
	Classes[c][CK_DEP] = DEP_CENTRE;
	AddClassItem(c, "GaussRifle", 1);
	AddClassItem(c, "EnergyAmmo", 300);
	AddClassItem(c, "Rifle", 1);
	AddClassItem(c, "RifleAmmo", 40);
	AddClassItem(c, "RifleGrenadeAmmo", 8);

	c = CLASS_CHEMWARRIOR;
	Classes[c][CK_NAME] = "Chem Warrior";
	Classes[c][CK_COST] = 550;
	Classes[c][CK_SPEED] = 0.7;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_CHEM;
	Classes[c][CK_DEP] = DEP_BARRACKS;
	AddClassItem(c, "ChemicalSprayer", 1);
	AddClassItem(c, "ChemicalAmmo", 200);
	AddClassItem(c, "ChemicalGrenadeAmmo", 4);
	AddClassItem(c, "SubMachineGun", 1);
	AddClassItem(c, "SubAmmo", 225);

	c = CLASS_SHOCKTROOPER;
	Classes[c][CK_NAME] = "Shock Trooper";
	Classes[c][CK_COST] = 600;
	Classes[c][CK_SPEED] = 0.7;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_LASER;
	Classes[c][CK_DEP] = DEP_CENTRE;
	Classes[c][CK_C4] = 2;
	AddClassItem(c, "ShockRifle", 1);
	AddClassItem(c, "EnergyAmmo", 300);
	AddClassItem(c, "SubMachineGun", 1);
	AddClassItem(c, "SubAmmo", 225);

	c = CLASS_COMMANDO;
	Classes[c][CK_NAME] = "Commando";
	Classes[c][CK_COST] = 1000;
	Classes[c][CK_SPEED] = 0.85;
	Classes[c][CK_GERNADES] = 4;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_C4] = 2;
	Classes[c][CK_FLAGS] = (CF_CANTPILOT);
	Classes[c][CK_DEP] = DEP_CENTRE;
	AddClassItem(c, "GaussRifle", 1);
	AddClassItem(c, "EnergyAmmo", 300);
	AddClassItem(c, "MissileLauncher", 1);
	AddClassItem(c, "MissileAmmo", 20);
	AddClassItem(c, "GatlingGun", 1);
	AddClassItem(c, "ChainAmmo", 250);
	AddClassItem(c, "Rifle", 1);
	AddClassItem(c, "RifleAmmo", 40);
	AddClassItem(c, "RifleGrenadeAmmo", 8);

	c = CLASS_SHOTGUNNER;
	Classes[c][CK_NAME] = "Shotgunner";
	Classes[c][CK_SPEED] = 0.85;
	AddClassItem(c, "Boomstick", 1);
	AddClassItem(c, "ShellsAmmo", 32);

	c = CLASS_SUICIDEBOMBER;
	Classes[c][CK_NAME] = "Suicide Bomber";
	Classes[c][CK_COST] = 1750;
	Classes[c][CK_C4] = 0;
	Classes[c][CK_GERNADES] = 0;
	Classes[c][CK_FLAGS] = (CF_CANTPILOT);
	AddClassItem(c, "BombPack", 1);

	c = CLASS_SNIPER;
	Classes[c][CK_NAME] = "Sniper";
	Classes[c][CK_COST] = 750;
	Classes[c][CK_SPEED] = 0.675;
	Classes[c][CK_DEP] = DEP_BARRACKS;
	Classes[c][CK_ARMORNUM] = 1;
	Classes[c][CK_GERNADES] = 2;
	AddClassItem(c, "SniperRifle", 1);
	AddClassItem(c, "SniperAmmo", 40);
	AddClassItem(c, "SubMachineGun", 1);
	AddClassItem(c, "SubAmmo", 225);

	c = CLASS_UTILITYGUY;
	Classes[c][CK_NAME] = "Utility Guy";
	Classes[c][CK_COST] = 650;
	Classes[c][CK_SPEED] = 0.75;
	Classes[c][CK_FLAGS] = (CF_SUPPORT | CF_CANTPILOT);
	Classes[c][CK_GERNADES] = 2; // why does a support class have two nades? :?
	Classes[c][CK_ARMORNUM] = 2;
	AddClassItem(c, "UtilityGun", 1);
	AddClassItem(c, "Utility_Ammo", 75);
	AddClassItem(c, "RepairGun", 1);

	c = CLASS_DEMOEXPERT;
	Classes[c][CK_NAME] = "Demolitions Expert";
	Classes[c][CK_COST] = 550;
	Classes[c][CK_SPEED] = 0.75;
	Classes[c][CK_FLAGS] = (CF_SUPPORT | CF_CANTPILOT);
	Classes[c][CK_C4] = 2;
	Classes[c][CK_GERNADES] = 4;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_EXPLO;
	AddClassItem(c, "BombSquadGun", 1);
	AddClassItem(c, "ProxyMine", 6);
	AddClassItem(c, "ProxyMineCount", 6);
	AddClassItem(c, "RemoteC4", 1);
	AddClassItem(c, "RemoteC4Ammo", 5);
	AddClassItem(c, "Boomstick", 1);
	AddClassItem(c, "ShellsAmmo", 32);

	c = CLASS_MEDIC;
	Classes[c][CK_NAME] = "Field Medic";
	Classes[c][CK_COST] = 300;
	Classes[c][CK_SPEED] = 0.85;
	Classes[c][CK_FLAGS] = (CF_SUPPORT | CF_HEALTHREGEN);
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_CHEM;
	AddClassItem(c, "HealGun", 1);
	AddClassItem(c, "HealingRadiusItem", 1);
	AddClassItem(c, "HealingRadiusCount", 1);
	AddClassItem(c, "TiberiumAutorifleWeak", 1);
	AddClassItem(c, "TE21CalAmmo", 120);

	c = CLASS_LASERCHAINGUNNER;
	Classes[c][CK_NAME] = "Laser Chaingunner";
	Classes[c][CK_COST] = 750;
	Classes[c][CK_SPEED] = 0.75;
	Classes[c][CK_DEP] = DEP_CENTRE;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_C4] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_LASER;
	AddClassItem(c, "LaserChaingun", 1);
	AddClassItem(c, "EnergyAmmo", 300);

	c = CLASS_JUMPJET;
	Classes[c][CK_NAME] = "Jet Trooper";
	Classes[c][CK_COST] = 600;
	Classes[c][CK_SPEED] = 0.65;
	Classes[c][CK_DEP] = DEP_BARRACKS;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	AddClassItem(c, "AssaultRifle", 1);
	AddClassItem(c, "ARAmmo", 120);
	AddClassItem(c, "Rifle", 1);
	AddClassItem(c, "RifleAmmo", 40);
	AddClassItem(c, "RifleGrenadeAmmo", 8);
	AddClassItem(c, "Jetpack", 1);
	AddClassItem(c, "JetpackFuel", 100);

	c = CLASS_TIBRIFLE;
	Classes[c][CK_NAME] = "Tiberium Gunner";
	Classes[c][CK_COST] = 400;
	Classes[c][CK_SPEED] = 0.8;
	Classes[c][CK_DEP] = DEP_BARRACKS;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 1;
	Classes[c][CK_ARMORMOD] = ARMOD_CHEM;
	AddClassItem(c, "TiberiumAutorifle", 1);
	AddClassItem(c, "TE21CalAmmo", 120);

	c = CLASS_DOUBLESHOTGUNNER;
	Classes[c][CK_NAME] = "Double Shotgunner";
	Classes[c][CK_COST] = 200;
	Classes[c][CK_SPEED] = 0.8;
	Classes[c][CK_ARMORNUM] = 1;
	AddClassItem(c, "DoubleShotgun", 1);
	AddClassItem(c, "ShellsAmmo", 32);

	c = CLASS_PLASMAGUNNER;
	Classes[c][CK_NAME] = "Plasma Gunner";
	Classes[c][CK_COST] = 800;
	Classes[c][CK_SPEED] = 0.7;
	Classes[c][CK_DEP] = DEP_CENTRE;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_C4] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_LASER;
	AddClassItem(c, "PlasmaGun", 1);
	AddClassItem(c, "EnergyAmmo", 300);

	c = CLASS_ARTILLERY;
	Classes[c][CK_NAME] = "Artillery Soldier";
	Classes[c][CK_COST] = 600;
	Classes[c][CK_SPEED] = 0.7;
	Classes[c][CK_DEP] = DEP_BARRACKS;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_ARMORMOD] = ARMOD_EXPLO;
	AddClassItem(c, "ArtilleryCannon", 1);
	AddClassItem(c, "ArtilleryShellAmmo", 40);
	AddClassItem(c, "Rifle", 1);
	AddClassItem(c, "RifleAmmo", 40);
	AddClassItem(c, "RifleGrenadeAmmo", 8);

	c = CLASS_TIMECOP;
	Classes[c][CK_NAME] = "Time Cop";
	Classes[c][CK_COST] = 2000;
	Classes[c][CK_SPEED] = 0.9;
	Classes[c][CK_DEP] = DEP_CENTRE;
	Classes[c][CK_GERNADES] = 4;
	Classes[c][CK_ARMORNUM] = 2;
	Classes[c][CK_C4] = 2;
	AddClassItem(c, "TimeGun", 1);
	AddClassItem(c, "TimeGunAmmo", 100);
	AddClassItem(c, "AssaultRifle", 1);
	AddClassItem(c, "ARAmmo", 150);

	c = CLASS_ADVHARVESTER;
	Classes[c][CK_NAME] = "Advanced Harvester";
	Classes[c][CK_COST] = 750;
	Classes[c][CK_SPEED] = 0.9;
	Classes[c][CK_DEP] = DEP_REFINERY;
	Classes[c][CK_GERNADES] = 2;
	Classes[c][CK_ARMORNUM] = 1;
	Classes[c][CK_ARMORMOD] = ARMOD_CHEM;
	Classes[c][CK_FLAGS] = (CF_HARVESTER | CF_SUPPORT);
	AddClassItem(c, "AssaultRifle", 1);
	AddClassItem(c, "SubAmmo", 225);
	AddClassItem(c, "SubMachineGun", 1);

	c = CLASS_HARVESTER;
	Classes[c][CK_NAME] = "Tiberium Harvester";
	Classes[c][CK_SPEED] = 0.65;
	Classes[c][CK_DEP] = DEP_REFINERY;
	Classes[c][CK_ARMORMOD] = ARMOD_CHEM;
	Classes[c][CK_FLAGS] = (CF_HARVESTER | CF_SUPPORT);
	AddClassItem(c, "SubMachineGun", 1);
	AddClassItem(c, "AMGAmmo", 120);

	c = ADDON_CHAINSAW;
	Classes[c][CK_NAME] = "Chainsaw";
	Classes[c][CK_FLAGS] = (CF_ADDON | CF_NOMENUEXIT);
	Classes[c][CK_COST] = 250;
	AddClassItem(c, "EagerBeaver", 1);

	c = ADDON_TIBRIFLE;
	Classes[c][CK_NAME] = "Tiberium Rifle";
	Classes[c][CK_FLAGS] = (CF_ADDON | CF_NOMENUEXIT);
	Classes[c][CK_COST] = 300;
	AddClassItem(c, "TiberiumAutorifleWeak", 1);

	c = ADDON_ARTILLERY;
	Classes[c][CK_NAME] = "Artillery Cannon";
	Classes[c][CK_FLAGS] = (CF_ADDON | CF_NOMENUEXIT);
	Classes[c][CK_COST] = 550;
	AddClassItem(c, "ArtilleryCannon", 1);

	c = ADDON_BEACON;
	Classes[c][CK_NAME] = "Team Beacon";
	Classes[c][CK_FLAGS] = (CF_ADDON | CF_NOMENUEXIT);
	Classes[c][CK_COST] = 1750;
	AddClassItem(c, "TeamBeaconGiver", 1);

	c = ADDON_PLASCAN;
	Classes[c][CK_NAME] = "Plasma Cannon";
	Classes[c][CK_FLAGS] = (CF_ADDON | CF_NOMENUEXIT);
	Classes[c][CK_COST] = 1500;
	AddClassItem(c, "PlasmaCannon", 1);

	c = ADDON_ARMOUR;
	Classes[c][CK_NAME] = "Armour Upgrade";
	Classes[c][CK_FLAGS] = (CF_ADDON | CF_NOMENUEXIT);
	Classes[c][CK_COST] = 250;
	AddClassItem(c, "HasArmorUpgrade", 1); //useless
}

function void LoadResearchDefinitions (void)
{
	int c;

	c = RES_ENHANCEDREF;
	Researches[c][CK_NAME] = "Enhanced Refining";
	Researches[c][CK_COST] = 2000;
	Researches[c][CK_DESC] = "Uses new technology to\nincrease the value\nof Tiberium.";

	c = RES_ADVMECHS;
	Researches[c][CK_NAME] = "Advanced Mechs";
	Researches[c][CK_COST] = 2000;
	Researches[c][CK_DESC] = "New Mech chassis and \nhardened metal plating.\nEnables construction of\nlarger Mechs.";

	c = RES_OBBYRES;
	Researches[c][CK_NAME] = "Obelisk/Telsa Restore";
	Researches[c][CK_COST] = 8000;
	Researches[c][CK_DESC] = "Restores the Obelisk/Tesla Coil\nif it is destroyed.";

	c = RES_HPREGEN;
	Researches[c][CK_NAME] = "Health Regen";
	Researches[c][CK_COST] = 2250;
	Researches[c][CK_DESC] = "Gives your team 1hp/s\nHP regeneration.";

	c = RES_AMMOREGEN;
	Researches[c][CK_NAME] = "Ammo Regen";
	Researches[c][CK_COST] = 2250;
	Researches[c][CK_DESC] = "Gives your team slow\nammo regeneration.";

	c = RES_TIMEDC4;
	Researches[c][CK_NAME] = "+1 Timed C4";
	Researches[c][CK_COST] = 150;
	Researches[c][CK_DESC] = "An additional Timed C4\nexplosive.";

	c = RES_REPAIRGUN;
	Researches[c][CK_NAME] = "Adv. Repair Gun";
	Researches[c][CK_COST] = 200;
	Researches[c][CK_DESC] = "Upgrades your Repair\nGun to make it\nfaster.";

	c = RES_ADVTURR;
	Researches[c][CK_NAME] = "Adv. Turrets";
	Researches[c][CK_COST] = 2000;
	Researches[c][CK_DESC] = "Enables use of higher\nlevel turrets.";

	c = RES_MORETURR;
	Researches[c][CK_NAME] = "More Turrets";
	Researches[c][CK_COST] = 2000;
	Researches[c][CK_DESC] = "Increases turret cap\nby 10.";
}
