@ECHO OFF
SET where=%1
SET repo=%2
SET rn=%cd%
for /F "usebackq tokens=1,2 delims==" %%i in (`wmic os get LocalDateTime /VALUE 2^>NUL`) do if '.%%i.'=='.LocalDateTime.' set ldt=%%je
SET date=%ldt:~2,6%

echo CD to repo
cd %repo%

echo Gitting
git log --pretty=format:^%h > v_commit.tmp
SET /P commit=<v_commit.tmp

cd %rn%

del /F /Q %where%

(echo ^/^/Auto generated by acver.bat.)>>%where%
(echo.)>>%where%
(echo #define THETA_RELEASE %date%)>>%where%
(echo #define THETA_COMMIT %commit%)>>%where%
