#include "../version.h"
#include <string>
#include <iostream>
#include <stdio.h>
#include <cstdio>
#include <fstream>
#ifndef _MSC_VER
#include <cstdlib>
#endif

#ifndef __cplusplus
# error "Please use C++ to compile this tool."
#endif

enum {
	LANG_UNKNOWN = -1,
	LANG_CLIKE,
	LANG_BATCH,
	LANG_BASH
}

using std::string;
using std::ofstream;

int main (int argc, char *argv[])
{
    int language = -1;
    string comment = "";
	bool silent = false;

	if (argc == 3 + 1)
	{
		string thirdArg = string(argv[3]);

		silent = (thirdArg == "-s" || thirdArg == "--silent");
	}

	if (!silent) printf("Theta genver tool, by Sean\n");

    if (argc != 2 + 1 && !silent)
    {
        printf("Expected two arguments.\n");
        printf("Syntax: gitcommit <language: c | batch> <output file> [--silent]\n");
		printf("Got %d arguments instead.\n", argc);
		for (int i = 0; i < argc; i++)
		{
			printf("Argument %d: %s\n", i, argv[i]);
		}
        return 1;
    }

	if (string(argv[1]) == "c")
	{
		language = LANG_CLIKE;
		comment = "//";
	}
	else if (string(argv[1]) == "batch")
	{
		language = LANG_BATCH;
		comment = "::";
	}
	else if (string(argv[1]) == "bash")
	{
		language = LANG_BASH;
		comment = "#";
	}
    else
    {
        language = LANG_UNKNOWN;
        printf("Unknown language '%s'.\n", argv[1]);
        printf("Please note that the language parameter is case sensitive.\n");
		return 2;
    }

	ofstream fstr;
	if (!silent) printf("Opening file.\n");
#ifdef _MSC_VER
	fstr.open(string(argv[2]));
#else
	fstr.open(argv[2]);
#endif
	if (!silent) printf("Writing disclaimer.\n");
	fstr << comment << " This file was generated by genver.\n";
	fstr << comment << " Please don't modify this file.\n";

	if (!silent) printf("Writing version information.\n");
	if (language == LANG_CLIKE)
    {
        fstr << "#define VERSION_MAJOR " << VERSION_MAJOR << "\n";
        fstr << "#define VERSION_MINOR " << VERSION_MINOR << "\n";
        fstr << "#define VERSION_PATCH " << VERSION_PATCH << "\n";
        fstr << "#define VERSION_STRING \"" << VERSION_MAJOR << "." << VERSION_MINOR << "." << VERSION_PATCH << "\"\n";
    }
	else if (language == LANG_BATCH)
    {
        fstr << "SET VERSION_MAJOR=" << VERSION_MAJOR << "\n";
        fstr << "SET VERSION_MINOR=" << VERSION_MINOR << "\n";
        fstr << "SET VERSION_PATCH=" << VERSION_PATCH << "\n";
        fstr << "SET VERSION_STRING=" << VERSION_MAJOR << "." << VERSION_MINOR << "." << VERSION_PATCH << "\n";
    }
	else if (language == LANG_BASH)
    {
        fstr << "export VERSION_MAJOR=" << VERSION_MAJOR << "\n";
        fstr << "export VERSION_MINOR=" << VERSION_MINOR << "\n";
        fstr << "export VERSION_PATCH=" << VERSION_PATCH << "\n";
        fstr << "export VERSION_STRING=" << VERSION_MAJOR << "." << VERSION_MINOR << "." << VERSION_PATCH << "\n";
    }
	if (!silent) printf("Closing file.\n");
	fstr.close();
	return 0;
}
